spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: aliaksei
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true